2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_setup.py:_flush():70] Configure stats pid to 766951
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_setup.py:_flush():70] Loading settings from /home/cagri/.config/wandb/settings
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_setup.py:_flush():70] Loading settings from /home/cagri/Desktop/IS-584-Term-Project/wandb/settings
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/cagri/Desktop/IS-584-Term-Project/wandb/run-20250622_234902-gscfy9jz/logs/debug.log
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/cagri/Desktop/IS-584-Term-Project/wandb/run-20250622_234902-gscfy9jz/logs/debug-internal.log
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x75935db98140>
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_init.py:init():852] calling init triggers
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_init.py:init():857] wandb.init called with sweep_config: {'lora_alpha': 16, 'lora_dropout': 0.05, 'max_length': 1900, 'n_shots': 1, 'r': 2}
config: {'_wandb': {}}
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_init.py:init():893] starting backend
2025-06-22 23:49:02,735 INFO    Thread-8 (_run_job):766951 [wandb_init.py:init():897] sending inform_init request
2025-06-22 23:49:02,737 INFO    Thread-8 (_run_job):766951 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-06-22 23:49:02,737 INFO    Thread-8 (_run_job):766951 [wandb_init.py:init():907] backend started and connected
2025-06-22 23:49:02,738 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_config_callback():1436] config_cb None None {'lora_alpha': 16, 'lora_dropout': 0.05, 'max_length': 1900, 'n_shots': 1, 'r': 2}
2025-06-22 23:49:02,739 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-06-22 23:49:02,740 INFO    Thread-8 (_run_job):766951 [wandb_init.py:init():1005] updated telemetry
2025-06-22 23:49:02,743 INFO    Thread-8 (_run_job):766951 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-06-22 23:49:03,419 INFO    Thread-8 (_run_job):766951 [wandb_init.py:init():1104] starting run threads in backend
2025-06-22 23:49:03,514 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_console_start():2573] atexit reg
2025-06-22 23:49:03,514 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-06-22 23:49:03,514 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-06-22 23:49:03,514 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_redirect():2513] Redirects installed.
2025-06-22 23:49:03,515 INFO    Thread-8 (_run_job):766951 [wandb_init.py:init():1150] run started, returning control to user process
2025-06-22 23:49:56,573 INFO    MainThread:766951 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-22 23:50:01,299 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_finish():2321] finishing run e274028-metu-middle-east-technical-university/tinyllama-fewshot/gscfy9jz
2025-06-22 23:50:01,300 INFO    Thread-8 (_run_job):766951 [jupyter.py:save_history():477] not saving jupyter history
2025-06-22 23:50:01,300 INFO    Thread-8 (_run_job):766951 [jupyter.py:save_ipynb():401] not saving jupyter notebook
2025-06-22 23:50:01,300 INFO    Thread-8 (_run_job):766951 [wandb_init.py:_jupyter_teardown():628] cleaning up jupyter logic
2025-06-22 23:50:01,300 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_atexit_cleanup():2538] got exitcode: 1
2025-06-22 23:50:01,300 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_restore():2520] restore
2025-06-22 23:50:01,300 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_restore():2526] restore done
2025-06-22 23:50:01,301 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_restore():2520] restore
2025-06-22 23:50:01,301 INFO    Thread-8 (_run_job):766951 [wandb_run.py:_restore():2526] restore done
2025-06-22 23:50:01,301 ERROR   Thread-8 (_run_job):766951 [wandb_run.py:_atexit_cleanup():2559] Problem finishing run
Traceback (most recent call last):
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/ipykernel_766951/2830317507.py", line 118, in sweep_prompt_eval
    evaluate(val_dataset, model, tokenizer, name="Validation")
  File "/tmp/ipykernel_766951/2830317507.py", line 51, in evaluate
    print("Prompt token count:", len(tokenizer(prompt)["input_ids"]))
  File "/home/cagri/.local/lib/python3.12/site-packages/ipykernel/iostream.py", line 694, in write
    self._schedule_flush()
  File "/home/cagri/.local/lib/python3.12/site-packages/ipykernel/iostream.py", line 590, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/home/cagri/.local/lib/python3.12/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/home/cagri/.local/lib/python3.12/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_zmq.py", line 1081, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1123, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1268, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2550, in _atexit_cleanup
    self._on_finish()
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2801, in _on_finish
    with progress.progress_printer(
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/sdk/lib/progress.py", line 92, in progress_printer
    with printer.dynamic_text() as text_area:
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/cagri/.local/lib/python3.12/site-packages/wandb/sdk/lib/printer.py", line 465, in dynamic_text
    handle = self._ipython_display.display(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cagri/.local/lib/python3.12/site-packages/IPython/core/display_functions.py", line 285, in display
    publish_display_data(data=format_dict, metadata=md_dict, **kwargs)
  File "/home/cagri/.local/lib/python3.12/site-packages/IPython/core/display_functions.py", line 73, in publish_display_data
    display_pub.publish(
  File "/home/cagri/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 103, in publish
    self._flush_streams()
  File "/home/cagri/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 66, in _flush_streams
    sys.stdout.flush()
  File "/home/cagri/.local/lib/python3.12/site-packages/ipykernel/iostream.py", line 604, in flush
    self.pub_thread.schedule(self._flush)
  File "/home/cagri/.local/lib/python3.12/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/home/cagri/.local/lib/python3.12/site-packages/zmq/sugar/socket.py", line 698, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_zmq.py", line 1081, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1123, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1268, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
2025-06-22 23:52:30,003 INFO    MsgRouterThr:766951 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
